import {chromium,webkit} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve('.'),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.json':'application/json'};
const server=createServer(async(req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/littlefolk\//,'/');if(p==='/')p='/index.html';const file=resolve(root,'.'+p);if(!file.startsWith(root+sep))throw Error('Not found');res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(await readFile(file));}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(4176,'127.0.0.1',r));await mkdir('artifacts',{recursive:true});const results=[];
try{for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await engine.launch({headless:true}),context=await browser.newContext({viewport:{width:1366,height:1024},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const tap=async(x,y)=>{const p=await page.evaluate(([x,y])=>__littlefolk.screenOf(x,y),[x,y]);await page.touchscreen.tap(p.x,p.y);};
 const drag=async(a,b)=>{const p=await page.evaluate(([a,b])=>[__littlefolk.screenOf(...a),__littlefolk.screenOf(...b)],[a,b]);await page.mouse.move(p[0].x,p[0].y);await page.mouse.down();await page.mouse.move(p[1].x,p[1].y,{steps:8});await page.mouse.up();};
 const panels=async()=>{await page.waitForTimeout(150);const v=await page.evaluate(()=>{const ps=[...document.querySelector('#contextRail').children].filter(e=>!e.hidden),dock=document.querySelector('.dock').getBoundingClientRect(),status=document.querySelector('#statusbar').getBoundingClientRect();return {count:ps.length,rects:ps.map(p=>({id:p.id,top:p.getBoundingClientRect().top,bottom:p.getBoundingClientRect().bottom,right:p.getBoundingClientRect().right})),dock:dock.top,status:status.bottom,w:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(v.count<=1,JSON.stringify(v));assert.equal(v.overflow,false);for(const p of v.rects){assert.ok(p.bottom<=v.dock-3,JSON.stringify(v));assert.ok(p.top>=v.status-1,JSON.stringify(v));assert.ok(p.right<=v.w,JSON.stringify(v));}};
 try{
  await page.goto('http://127.0.0.1:4176/littlefolk/?test=1');await page.waitForFunction(()=>window.__littlefolk);await page.locator('#beginBtn').tap();
  await page.evaluate(async()=>{const w=await import('./world.js');__littlefolk.restore(w.snapshot(w.createWorld(41728)));});
  await tap(20.5,19.5);await page.locator('#confirmBuild').tap();assert.equal(await page.evaluate(()=>__littlefolk.state.folk.length),1);
  await page.locator('[data-build="hut"]').hover();await page.waitForTimeout(100);assert.ok(await page.locator('#buildingPeek').innerText());await panels();await page.mouse.move(3,300);await page.locator('[data-category="Food"]').tap();await page.locator('[data-build="kitchen"]').tap();assert.match(await page.locator('#buildHint').innerText(),/2 vegetables|Feed the village/);await panels();await page.screenshot({path:`artifacts/${name}-harvest-building-guide.png`});await page.locator('#cancelBuild').tap();
  for(const n of [2,3,5,1]){await page.locator('#speedBtn').tap();assert.equal(await page.evaluate(()=>__littlefolk.speed),n);}
  await page.evaluate(()=>__littlefolk.setSpeed(5));const time=await page.evaluate(()=>__littlefolk.state.t);await page.waitForTimeout(1800);assert.ok(await page.evaluate(t=>__littlefolk.state.t>t+3,time),'5x simulation is advancing');await page.evaluate(()=>__littlefolk.setSpeed(1));
  await page.locator('#landBtn').tap();await drag([15.5,16.5],[18.5,18.5]);assert.equal(await page.locator('#clearAreaNow').isVisible(),true);await panels();await page.screenshot({path:`artifacts/${name}-harvest-area.png`});await page.locator('#clearAreaNow').tap();assert.equal(await page.evaluate(()=>__littlefolk.state.tiles[17*44+16].node),null);
  await drag([17.5,22.5],[19.5,24.5]);await page.locator('#harvestArea').tap();assert.equal(await page.evaluate(()=>__littlefolk.state.tiles[23*44+18].node?.clear),true);await page.locator('#cancelAllClearing').tap();assert.equal(await page.evaluate(()=>!!__littlefolk.state.tiles[23*44+18].node?.clear),false);await page.locator('#landClose').tap();
  await page.evaluate(()=>{const s=__littlefolk.state;s.wood=2000;s.stone=2000;s.delivered=2000;});
  for(const [kind,x,y] of [['vegetable',17,14],['kitchen',24,14],['orchard',24,19],['fishery',28,12]]){await page.locator('[data-category="Food"]').tap();await page.locator(`[data-build="${kind}"]`).tap();await tap(x+.5,y+.5);await page.locator('#confirmBuild').tap();assert.ok(await page.evaluate(t=>__littlefolk.state.buildings.some(b=>b.type===t),kind));}
  assert.equal(await page.evaluate(()=>__littlefolk.state.industry.routes.length),5);await page.evaluate(()=>__littlefolk.advance(150));assert.ok(await page.evaluate(()=>__littlefolk.state.industry.goods.meal>0));assert.ok(await page.evaluate(()=>__littlefolk.state.industry.goods.fish>0));
  await tap(24.5,14.5);await panels();assert.match(await page.locator('#inspector').innerText(),/No wind needed|cookhouse/);await page.screenshot({path:`artifacts/${name}-harvest-cookhouse.png`});
  await page.locator('#villagePulse').tap();assert.equal(await page.locator('#contextRail').isVisible(),false);await page.locator('[data-vtab="chains"]').tap();assert.ok(await page.locator('.chainStage').count()>5);assert.ok(await page.locator('.chainPlus').count()>0);await page.screenshot({path:`artifacts/${name}-harvest-chains.png`});await page.locator('#closeVillage').tap();
  await page.evaluate(()=>{const s=__littlefolk.state;s.industry.tier=3;s.industry.postcards=3;for(const k of ['meal','berry','fish','plank','brick','iron','gear'])s.industry.goods[k]=1000;});
  await page.locator('#villageBoardBtn').tap();for(const id of ['picnic','arch','fountain','parade','fair']){await page.locator(`[data-project="${id}"]`).tap();assert.ok(await page.evaluate(id=>__littlefolk.state.bloom.projects.includes(id),id));}
  await page.locator('[data-theme="2"]').tap();assert.equal(await page.evaluate(()=>__littlefolk.state.bloom.theme),2);await page.screenshot({path:`artifacts/${name}-harvest-wishes.png`});await page.locator('[data-vtab="supper"]').tap();await page.screenshot({path:`artifacts/${name}-harvest-supper.png`});await page.locator('#closeVillage').tap();
  await page.evaluate(()=>{__littlefolk.state.bloom.mood=95;__littlefolk.state.bloom.festUntil=__littlefolk.state.t+55;});await page.waitForTimeout(200);await page.screenshot({path:`artifacts/${name}-harvest-flourishing.png`});
  for(const size of [{width:1024,height:1366},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.locator('#landBtn').tap();await panels();await page.screenshot({path:`artifacts/${name}-harvest-${size.width}x${size.height}.png`});await page.locator('#landClose').tap();await page.locator('#villageBoardBtn').tap();assert.equal(await page.locator('.sheetback:not([hidden])').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#closeVillage').tap();}
  await page.setViewportSize({width:1366,height:1024});for(let n=0;n<10;n++){await page.locator('[data-category="Food"]').tap();await page.locator('[data-build="vegetable"]').tap();await page.locator('#cancelBuild').tap();await page.locator('#villageBoardBtn').tap();await page.locator('#closeVillage').tap();}
  const saved=await page.evaluate(()=>{__littlefolk.save();return {projects:__littlefolk.state.bloom.projects,theme:__littlefolk.state.bloom.theme,routes:__littlefolk.state.industry.routes.length};});await page.reload();await page.waitForFunction(()=>window.__littlefolk);assert.deepEqual(await page.evaluate(()=>__littlefolk.state.bloom.projects),saved.projects);assert.equal(await page.evaluate(()=>__littlefolk.state.bloom.theme),saved.theme);assert.equal(await page.evaluate(()=>__littlefolk.state.industry.routes.length),saved.routes);assert.equal(await page.evaluate(()=>__littlefolk.state.tiles[17*44+16].node),null);assert.equal(await page.evaluate(()=>__littlefolk.fault),false);assert.deepEqual(errors,[]);
  const legacy=await page.evaluate(async()=>{const w=await import('./world.js'),s=w.createWorld(41728);w.place(s,'hut',20,19);const raw=w.snapshot(s);delete raw.bloom;for(const k of ['veg','meal','berry','fish']){delete raw.industry.goods[k];delete raw.industry.limits[k];}return JSON.stringify(raw);});
  const migration=await browser.newContext({viewport:{width:1024,height:1366},hasTouch:true});await migration.addInitScript(raw=>{localStorage.setItem('littlefolk.v2.save',raw);},legacy);const mp=await migration.newPage();await mp.goto('http://127.0.0.1:4176/littlefolk/?test=1');await mp.waitForFunction(()=>window.__littlefolk);assert.equal(await mp.evaluate(()=>__littlefolk.state.industry.goods.meal),2);await mp.evaluate(()=>__littlefolk.save());assert.equal(await mp.evaluate(()=>localStorage.getItem('littlefolk.pre22.save')),legacy);await migration.close();
  results.push({engine:name,result:'passed',coverage:['hover building knowledge','tap building recipes and purpose','5x simulation','rectangular area selection and instant half-yield clearing','cancel autonomous area orders','automatic physical food logistics','parallel ingredient diagrams','project purchases and permanent rewards','theme changes','single context panel bounds on tablet, phone and landscape','repeated touch actions','save persistence of food, projects and cleared land','2.1 migration and preserved pre-update backup']});
 }catch(error){await page.screenshot({path:`artifacts/${name}-harvest-failure.png`}).catch(()=>{});results.push({engine:name,result:'failed',error:String(error),pageErrors:errors});throw error;}finally{await context.close();await browser.close();}
}}finally{await writeFile('artifacts/harvest-browser-results.json',JSON.stringify(results,null,2));await new Promise(r=>server.close(r));}console.log(JSON.stringify(results,null,2));
