import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,place,placement,step,snapshot,restore,W,H} from '../world.js';
import {connect,stepIndustry,stock,research,removeRoute,demolish,RECIPES,upgradeLogistics} from '../industry.js';
function village(){const s=createWorld(41728);for(let y=10;y<28;y++)for(let x=10;x<36;x++){const t=s.tiles[y*W+x];t.ground='grass';t.node=null;}
  for(const [x,y,type] of [[10,12,'tree'],[11,20,'stone']])s.tiles[y*W+x].node={type,amount:18,rest:0};
  assert.ok(place(s,'hut',20,19).ok);s.wood=2000;s.stone=2000;s.delivered=1000;s.industry.tier=3;Object.assign(s.industry.goods,{plank:100,brick:100,iron:100,gear:100});return s;}
const advance=(s,time)=>{for(let n=0;n<time*10;n++){s.t+=.1;stepIndustry(s,.1);}};
const build=(s,type,x,y)=>{const r=place(s,type,x,y);assert.ok(r.ok,r.reason);return s.buildings.at(-1);};
function millLine(){const s=village();s.industry.goods={};s.industry.tier=0;const hub=s.buildings[0],wind=build(s,'windmill',24,19),saw=build(s,'sawmill',24,14);return {s,hub,wind,saw};}
test('v1 migration retains village and initializes empty industry without changing the original snapshot',()=>{const s=village();const raw=snapshot(s);raw.version=1;delete raw.industry;raw.buildings=raw.buildings.filter(b=>b.type==='hut');const before=JSON.stringify(raw),r=restore(raw);assert.equal(r.version,2);assert.equal(r.folk[0].name,'Pip');assert.equal(r.wood,raw.wood);assert.equal(r.industry.tier,0);assert.equal(JSON.stringify(raw),before);});
test('factory placement gates research and refined costs without spending anything',()=>{const {s}=millLine();const before=s.wood;assert.equal(place(s,'smelter',28,14).ok,false);assert.equal(s.wood,before);s.industry.tier=1;assert.equal(place(s,'smelter',28,14).ok,false);assert.equal(s.wood,before);});
test('sawmill has no magic inputs and needs real wind power',()=>{const {s,saw}=millLine();advance(s,30);assert.equal(s.industry.totals.plank||0,0);s.industry.machines[saw.id].input.wood=4;s.buildings=s.buildings.filter(b=>b.type!=='windmill');advance(s,20);assert.equal(s.industry.totals.plank||0,0);assert.equal(s.industry.machines[saw.id].input.wood,4);});
test('two real routes close the wood-plank-home loop and preserve exact mass balance',()=>{const {s,hub,saw}=millLine();const initial=s.wood;assert.ok(connect(s,hub.id,saw.id).ok);assert.ok(connect(s,saw.id,hub.id).ok);advance(s,160);assert.ok(stock(s,'plank')>4);const m=s.industry.machines[saw.id],produced=s.industry.totals.plank;const transitWood=s.industry.shipments.filter(p=>p.item==='wood').reduce((a,p)=>a+p.amount,0);assert.equal(initial-s.wood,produced*2+(m.batch?2:0)+(m.input.wood||0)+transitWood);assert.ok(s.industry.shipments.every(p=>p.amount>0));});
test('cargo remains physically in transit and removing a route recovers it exactly once',()=>{const {s,hub,saw}=millLine();const initial=s.wood;connect(s,hub.id,saw.id);advance(s,.1);assert.equal(s.industry.machines[saw.id].input.wood||0,0);assert.equal(s.industry.shipments.length,1);assert.equal(initial-s.wood,3);removeRoute(s,s.industry.routes[0].id);assert.equal(s.wood,initial);assert.equal(s.industry.shipments.length,0);removeRoute(s,1);assert.equal(s.wood,initial);});
test('reserve protection prevents factories from spending home-building wood',()=>{const {s,hub,saw}=millLine();s.wood=14;connect(s,hub.id,saw.id);advance(s,70);assert.equal(s.wood,12);assert.ok((s.industry.machines[saw.id].output.plank||0)<=1);});
test('finite buffers apply backpressure without swallowing resources',()=>{const {s,hub,saw}=millLine();connect(s,hub.id,saw.id);advance(s,600);const m=s.industry.machines[saw.id];assert.equal(m.output.plank,24);assert.ok(m.input.wood<=24);assert.equal(m.status,'Output full · add a route');assert.equal(s.industry.totals.plank,24);});
test('power is shared fairly, and more windmills resolve overload',()=>{const s=village();build(s,'windmill',20,15);const a=build(s,'smelter',16,14),b=build(s,'smelter',24,14),c=build(s,'gearworks',16,18),d=build(s,'gearworks',24,18),e=build(s,'gearworks',16,22);advance(s,.1);assert.equal(s.industry.machines[a.id].power,.8);assert.equal(s.industry.machines[e.id].power,.8);build(s,'windmill',20,22);advance(s,.1);assert.equal(s.industry.machines[a.id].power,1);});
test('research consumes delivered goods, not local buffers',()=>{const {s,saw}=millLine();s.industry.machines[saw.id].output.plank=20;assert.equal(research(s).ok,false);s.industry.goods={plank:12,brick:8};assert.equal(research(s).ok,true);assert.equal(s.industry.tier,1);assert.equal(stock(s,'plank'),0);assert.equal(research(s).ok,false);});
test('save/restore preserves in-process inputs, production progress and traveling cargo',()=>{const {s,hub,saw}=millLine();connect(s,hub.id,saw.id);connect(s,saw.id,hub.id);advance(s,32);const raw=snapshot(s),r=restore(raw);assert.equal(r.wood,s.wood);assert.equal(r.industry.shipments.length,s.industry.shipments.length);assert.deepEqual(r.industry.machines[saw.id].input,s.industry.machines[saw.id].input);assert.equal(r.industry.machines[saw.id].batch,s.industry.machines[saw.id].batch);assert.equal(r.industry.machines[saw.id].progress,s.industry.machines[saw.id].progress);advance(r,80);assert.ok(stock(r,'plank')>0);});
test('malformed cargo and workshop saves fail before replacement',()=>{const {s,hub,saw}=millLine();connect(s,hub.id,saw.id);advance(s,.1);const raw=snapshot(s);raw.industry.shipments[0].item='__proto__';assert.throws(()=>restore(raw));const bad=snapshot(s);bad.industry.machines[saw.id].input.wood=Infinity;assert.throws(()=>restore(bad));const bad2=snapshot(s);bad2.industry.routes[0].from=999999;assert.throws(()=>restore(bad2));});
test('reclaim recovers ingredients in an active batch and does not evict residents',()=>{const {s,hub,saw}=millLine();const m=s.industry.machines[saw.id];m.input.wood=4;advance(s,2);assert.ok(m.batch);const before=s.wood;assert.ok(demolish(s,saw.id).ok);assert.equal(s.wood,before+4+9);assert.equal(demolish(s,hub.id).ok,false);});
test('star post consumes a real batch and creates a named postcard memory',()=>{const s=village();build(s,'windmill',24,19);const post=build(s,'skypost',24,14),m=s.industry.machines[post.id];m.input={plank:2,gear:1};advance(s,18);assert.equal(s.industry.postcards,1);assert.equal(m.input.plank,0);assert.ok(s.memories.some(m=>m.text.includes('little light')));assert.ok(s.events.some(e=>e.type==='postcard'));});
test('wagon upgrades are gated, paid, and increase finite capacity',()=>{const s=village();s.industry.tier=1;assert.equal(upgradeLogistics(s).ok,false);s.industry.tier=2;assert.ok(upgradeLogistics(s).ok);assert.equal(s.industry.logistics,1);assert.equal(upgradeLogistics(s).ok,false);s.industry.tier=3;assert.ok(upgradeLogistics(s).ok);assert.equal(upgradeLogistics(s).ok,false);});
test('long-running multi-stage village remains finite and all cargo can round-trip a save',()=>{const s=village(),hub=s.buildings[0];build(s,'windmill',20,14);build(s,'windmill',24,21);const saw=build(s,'sawmill',24,14),brick=build(s,'mason',17,14),kiln=build(s,'kiln',28,14),mine=build(s,'mine',14,19),smelter=build(s,'smelter',28,18),gears=build(s,'gearworks',28,22);
 for(const [a,b] of [[hub,saw],[saw,hub],[hub,brick],[brick,hub],[hub,kiln],[kiln,smelter],[mine,smelter],[smelter,gears],[saw,gears],[gears,hub]])assert.ok(connect(s,a.id,b.id).ok);
 s.industry.goods={};for(let n=0;n<18000;n++)step(s,.1);assert.ok(s.industry.totals.iron>0);assert.ok(s.industry.totals.gear>0);assert.ok(s.industry.history.length<=800);assert.ok(s.industry.shipments.length<=s.industry.routes.length*3);assert.doesNotThrow(()=>restore(snapshot(s)));assert.ok(Number.isFinite(s.wood));});
