import {chromium,webkit} from 'playwright';
import {createServer} from 'node:http';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {resolve,extname,sep} from 'node:path';import assert from 'node:assert/strict';
const root=resolve('.'),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.json':'application/json'};
const server=createServer(async(req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/littlefolk\//,'/');if(p==='/')p='/index.html';const file=resolve(root,'.'+p);if(!file.startsWith(root+sep))throw Error('Not found');res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(await readFile(file));}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(4177,'127.0.0.1',r));await mkdir('artifacts',{recursive:true});const results=[];
try{for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await engine.launch({headless:true}),context=await browser.newContext({viewport:{width:1366,height:1024},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const tap=async(x,y)=>{const p=await page.evaluate(([x,y])=>__littlefolk.screenOf(x,y),[x,y]);await page.touchscreen.tap(p.x,p.y);};
 const panels=async()=>{await page.waitForTimeout(180);const v=await page.evaluate(()=>{const ps=[...document.querySelector('#contextRail').children].filter(e=>!e.hidden),dock=document.querySelector('.dock').getBoundingClientRect(),status=document.querySelector('#statusbar').getBoundingClientRect();return {count:ps.length,rects:ps.map(p=>({id:p.id,top:p.getBoundingClientRect().top,bottom:p.getBoundingClientRect().bottom,right:p.getBoundingClientRect().right})),dock:dock.top,status:status.bottom,w:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(v.count<=1,JSON.stringify(v));assert.equal(v.overflow,false);for(const p of v.rects){assert.ok(p.bottom<=v.dock-3,JSON.stringify(v));assert.ok(p.top>=v.status-1,JSON.stringify(v));assert.ok(p.right<=v.w,JSON.stringify(v));}};
 try{
  await page.goto('http://127.0.0.1:4177/littlefolk/?test=1');await page.waitForFunction(()=>window.__littlefolk);await page.locator('#beginBtn').tap();
  await page.evaluate(async()=>{const w=await import('./world.js');const s=w.createWorld(41728);w.place(s,'hut',20,19);s.wood=s.stone=s.delivered=2000;__littlefolk.restore(w.snapshot(s));});await page.locator('#cancelBuild').tap();
  await page.locator('[data-category="Village"]').tap();await page.locator('[data-build="quarry"]').tap();await tap(23.5,12.5);await panels();assert.match(await page.locator('#buildHint').innerText(),/Fits/);assert.ok(await page.locator('#confirmBuild').isEnabled());await page.screenshot({path:`artifacts/${name}-works-plot.png`});await page.locator('#confirmBuild').tap();
  for(const [type,x,y] of [['windmill',17,14],['sawmill',24,14],['mason',27,14],['vegetable',24,19],['kitchen',27,22]]){
   const cat=['vegetable','kitchen'].includes(type)?'Food':'Craft';await page.locator(`[data-category="${cat}"]`).tap();await page.locator(`[data-build="${type}"]`).tap();await tap(x+.5,y+.5);await page.locator('#confirmBuild').tap();
  }
  await page.evaluate(()=>__littlefolk.advance(80));await page.locator('#networkBtn').tap();assert.equal(await page.locator('#networkBtn').getAttribute('aria-pressed'),'true');await tap(24.5,14.5);await panels();assert.equal(await page.locator('.connectionRow').count(),2);assert.match(await page.locator('#connectionList').innerText(),/From|To/);await page.screenshot({path:`artifacts/${name}-works-network.png`});
  const paths=await page.evaluate(async()=>{const L=await import('./lanes.js'),w=await import('./world.js'),s=__littlefolk.state;const net=L.laneNetwork(s);return {cells:net.cells.size,valid:s.industry.routes.every(r=>r.path.every((p,j)=>w.walkable(s,Math.floor(p.x),Math.floor(p.y))&&(!j||Math.abs(p.x-r.path[j-1].x)+Math.abs(p.y-r.path[j-1].y)===1)))};});assert.ok(paths.cells>10);assert.ok(paths.valid);
  await page.locator('#closeInspect').tap();await page.locator('[data-category="Village"]').tap();await page.locator('[data-build="path"]').tap();const before=await page.evaluate(()=>__littlefolk.state.stone);await tap(23.5,23.5);await tap(26.5,25.5);await panels();assert.ok(await page.locator('#confirmPaving').isEnabled());await page.screenshot({path:`artifacts/${name}-works-paving.png`});await page.locator('#confirmPaving').tap();assert.ok(await page.evaluate(()=>__littlefolk.state.tiles[23*44+23].path));assert.ok(await page.evaluate(()=>__littlefolk.state.stone)<before);await page.locator('#cancelBuild').tap();
  await page.locator('#industryBtn').tap();await page.locator('[data-tab="routes"]').tap();await page.locator('#optimizeStorage').tap();await page.locator('#restoreFlow').tap();assert.equal(await page.locator('.sheetback:not([hidden])').count(),1);await page.locator('#closeIndustry').tap();
  for(const size of [{width:1024,height:1366},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.locator('[data-category="Craft"]').tap();await page.locator('[data-build="sawmill"]').tap();await panels();await page.screenshot({path:`artifacts/${name}-works-${size.width}x${size.height}.png`});await page.locator('#cancelBuild').tap();}
  await page.setViewportSize({width:1366,height:1024});for(let j=0;j<15;j++){await page.locator('[data-category="Craft"]').tap();await page.locator('[data-build="windmill"]').tap();await tap(30.5,21.5);await page.locator('#cancelBuild').tap();}const frames=await page.evaluate(()=>__littlefolk.frames);await page.waitForTimeout(600);assert.ok(await page.evaluate(()=>__littlefolk.frames)>frames);assert.equal(await page.evaluate(()=>__littlefolk.fault),false);
  const saved=await page.evaluate(()=>{__littlefolk.save();return __littlefolk.state.industry.routes.map(r=>[r.id,r.from,r.to]);});await page.reload();await page.waitForFunction(()=>window.__littlefolk);assert.deepEqual(await page.evaluate(()=>__littlefolk.state.industry.routes.map(r=>[r.id,r.from,r.to])),saved);assert.ok(await page.evaluate(()=>__littlefolk.state.tiles[23*44+23].path));assert.deepEqual(errors,[]);
  results.push({engine:name,result:'passed',coverage:['honest plot previews','real shared cardinal delivery lanes','input/output connection inspection','tap-to-plan whole paved walks','manual network preservation','stock-setting recovery','portrait and landscape panel bounds','repeated interactions and live frames','existing village and lane persistence']});
 }catch(error){await page.screenshot({path:`artifacts/${name}-works-failure.png`}).catch(()=>{});results.push({engine:name,result:'failed',error:String(error),pageErrors:errors});throw error;}finally{await context.close();await browser.close();}
}}finally{await writeFile('artifacts/works-browser-results.json',JSON.stringify(results,null,2));await new Promise(r=>server.close(r));}console.log(JSON.stringify(results,null,2));
