import {chromium,webkit} from 'playwright';
import {createServer} from 'node:http';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {resolve,extname,sep} from 'node:path';import assert from 'node:assert/strict';
const root=resolve('.'),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.json':'application/json'};
const server=createServer(async(req,res)=>{try{let path=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/littlefolk\//,'/');if(path==='/')path='/index.html';const file=resolve(root,'.'+path);if(!file.startsWith(root+sep))throw Error('Not found');res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(await readFile(file));}catch{res.writeHead(404);res.end('Not found');}});await new Promise(r=>server.listen(4175,'127.0.0.1',r));await mkdir('artifacts',{recursive:true});const results=[];
try{for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await engine.launch({headless:true}),context=await browser.newContext({viewport:{width:1366,height:1024},isMobile:true,hasTouch:true,acceptDownloads:true}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const tap=async(x,y)=>{const p=await page.evaluate(({x,y})=>window.__littlefolk.screenOf(x,y),{x,y});await page.touchscreen.tap(p.x,p.y);};
 const panels=async()=>{await page.waitForTimeout(150);const value=await page.evaluate(()=>{const panels=[...document.querySelector('#contextRail').children].filter(e=>!e.hidden),dock=document.querySelector('.dock').getBoundingClientRect(),status=document.querySelector('#statusbar').getBoundingClientRect();return {count:panels.length,rects:panels.map(p=>({id:p.id,top:p.getBoundingClientRect().top,bottom:p.getBoundingClientRect().bottom,right:p.getBoundingClientRect().right})),dock:dock.top,status:status.bottom,w:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(value.count<=1,JSON.stringify(value));assert.equal(value.overflow,false);for(const p of value.rects){assert.ok(p.bottom<=value.dock-3,JSON.stringify(value));assert.ok(p.top>=value.status,JSON.stringify(value));assert.ok(p.right<=value.w,JSON.stringify(value));}};
 try{
  await page.goto('http://127.0.0.1:4175/littlefolk/?test=1');await page.waitForFunction(()=>window.__littlefolk);await page.locator('#beginBtn').tap();await page.evaluate(async()=>{const w=await import('./world.js');window.__littlefolk.restore(w.snapshot(w.createWorld(41728)));});
  await tap(20.5,19.5);assert.equal(await page.evaluate(()=>window.__littlefolk.state.folk.length),0,'Preview does not spend or build');await panels();await page.screenshot({path:`artifacts/${name}-qol-preview.png`});await page.locator('#confirmBuild').tap();assert.equal(await page.evaluate(()=>window.__littlefolk.state.folk.length),1);
  await page.evaluate(()=>{const a=window.__littlefolk;a.advance(1800);a.state.wood=1000;a.state.stone=1000;a.state.delivered=1000;});
  for(const [kind,x,y] of [['windmill',17,14],['sawmill',24,14]]){await page.locator('[data-category="Craft"]').tap();await page.locator(`[data-build="${kind}"]`).tap();await tap(x+.5,y+.5);await page.locator('#confirmBuild').tap();}
  await tap(24.5,14.5);await panels();await page.locator('[data-action="storage"]').tap();assert.equal(await page.evaluate(()=>window.__littlefolk.state.industry.routes.length),2);await page.locator('[data-action="storage"]').tap();assert.equal(await page.evaluate(()=>window.__littlefolk.state.industry.routes.length),2);await page.evaluate(()=>window.__littlefolk.advance(90));assert.ok(await page.evaluate(()=>window.__littlefolk.state.industry.goods.plank>0));await panels();await page.screenshot({path:`artifacts/${name}-qol-factory.png`});
  const homeId=await page.evaluate(()=>window.__littlefolk.state.folk[0].home);await tap(20.5,19.5);await page.locator('[data-action="move"]').tap();await tap(24.5,19.5);await page.locator('#confirmBuild').tap();assert.equal(await page.evaluate(()=>window.__littlefolk.state.folk[0].home),homeId);assert.equal(await page.evaluate(id=>window.__littlefolk.state.buildings.find(b=>b.id===id).x,homeId),24);
  await page.locator('#landBtn').tap();await page.locator('[data-brush="0"]').tap();await tap(16.5,17.5);assert.equal(await page.evaluate(()=>window.__littlefolk.state.tiles[17*44+16].node.clear),true);await panels();await page.locator('#landUndo').tap();assert.equal(await page.evaluate(()=>window.__littlefolk.state.tiles[17*44+16].node.clear),false);await tap(16.5,17.5);await page.evaluate(()=>window.__littlefolk.advance(300));assert.equal(await page.evaluate(()=>window.__littlefolk.state.tiles[17*44+16].node),null);await page.screenshot({path:`artifacts/${name}-qol-clearing.png`});
  await page.locator('[data-land="plant"]').tap();await tap(20.5,15.5);assert.equal(await page.evaluate(()=>window.__littlefolk.state.tiles[15*44+20].node?.type),'tree');
  await page.locator('#industryBtn').tap();assert.equal(await page.locator('#contextRail').isVisible(),false);assert.equal(await page.locator('.sheetback:not([hidden])').count(),1);await page.locator('[data-tab="flow"]').tap();await page.locator('[data-reserve-input="wood"]').fill('7');await page.locator('[data-reserve-input="wood"]').press('Tab');assert.equal(await page.evaluate(()=>window.__littlefolk.state.industry.reserves.wood),7);assert.equal(await page.locator('#industryBack .modalFeedback').isVisible(),true);assert.equal(await page.locator('#toast').isVisible(),false);await page.locator('#closeIndustry').tap();
  for(const size of [{width:1024,height:1366},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.locator('#landBtn').tap();await panels();await page.screenshot({path:`artifacts/${name}-qol-${size.width}x${size.height}.png`});await page.locator('#landClose').tap();}
  await page.setViewportSize({width:1366,height:1024});
  for(let n=0;n<12;n++){await page.locator('[data-category="Village"]').tap();await page.locator('[data-build="hut"]').tap();await page.locator('#cancelBuild').tap();await page.locator('#settingsBtn').tap();await page.locator('[data-close="settingsBack"]').tap();await page.locator('#landBtn').tap();await page.locator('#landClose').tap();}
  const before=await page.evaluate(()=>{window.__littlefolk.save();return {population:window.__littlefolk.state.folk.length,home:window.__littlefolk.state.folk[0].home,routes:window.__littlefolk.state.industry.routes.length,planks:window.__littlefolk.state.industry.goods.plank};});await page.reload();await page.waitForFunction(()=>window.__littlefolk);assert.equal(await page.evaluate(()=>window.__littlefolk.state.tiles[17*44+16].node),null);assert.equal(await page.evaluate(()=>window.__littlefolk.state.folk[0].home),before.home);assert.equal(await page.evaluate(()=>window.__littlefolk.state.industry.routes.length),before.routes);assert.ok(await page.evaluate(()=>window.__littlefolk.state.industry.goods.plank)>=before.planks);assert.equal(await page.evaluate(()=>window.__littlefolk.fault),false);assert.deepEqual(errors,[]);
  results.push({engine:name,result:'passed',coverage:['two-stage touch placement without accidental spending','single non-overlapping context rail','idempotent one-tap real storage wiring','moving homes without eviction','autonomous permanent clearing and undo','replanting','visible reserve controls','modal feedback never overlays another panel','iPad portrait, phone and short landscape layouts','rapid repeated UI interactions','save persistence of cleared land, residents and cargo routes']});
 }catch(error){await page.screenshot({path:`artifacts/${name}-qol-failure.png`}).catch(()=>{});results.push({engine:name,result:'failed',error:String(error),pageErrors:errors});throw error;}finally{await context.close();await browser.close();}
}}finally{await writeFile('artifacts/qol-browser-results.json',JSON.stringify(results,null,2));await new Promise(r=>server.close(r));}console.log(JSON.stringify(results,null,2));
